DROP DATABASE IF EXISTS MyCamp;
CREATE DATABASE IF NOT EXISTS MyCamp;
USE MyCamp;

CREATE TABLE users(
   id INT NOT NULL AUTO_INCREMENT,
   email VARCHAR(100) NOT NULL,
   password VARCHAR(100) NOT NULL,
   PRIMARY KEY ( id )
);

CREATE TABLE projects(
   id INT NOT NULL AUTO_INCREMENT,
   user_id INT NOT NULL REFERENCES users(id),
   name VARCHAR(100) NOT NULL,
   url VARCHAR(100) NOT NULL,
   git VARCHAR(1024) NOT NULL,
   env VARCHAR(20) NOT NULL,
   PRIMARY KEY ( id )
);
